:source-language: lisp
:uri-flymake: https://www.gnu.org/software/emacs/manual/html_node/emacs/Flymake.html
:uri-flycheck: https://www.flycheck.org/
:uri-flycheck-eldev: https://github.com/flycheck/flycheck-eldev
:uri-eldev: https://github.com/emacs-eldev/eldev
:uri-eldev-installation: https://github.com/emacs-eldev/eldev#installation
:uri-melpa-stable: https://stable.melpa.org/#/flymake-eldev
:uri-melpa-unstable: https://melpa.org/#/flymake-eldev

= flymake-eldev

image:https://img.shields.io/badge/license-GPL_3-green.svg[License: GPL 3, link=http://www.gnu.org/licenses/gpl-3.0.txt]
image:http://stable.melpa.org/packages/flymake-eldev-badge.svg[Melpa Stable, link=http://stable.melpa.org/#/flymake-eldev]
image:https://github.com/emacs-eldev/flymake-eldev/workflows/CI/badge.svg[Build status, link=https://github.com/emacs-eldev/flymake-eldev/actions?query=workflow%3ACI]

Make {uri-flymake}[Flymake] use proper dependencies in
{uri-eldev}[Eldev] projects.

For a project to be detected, it must contain file `Eldev` or
`Eldev-local` in its root directory, even if Eldev doesn’t strictly
require that.

TIP: If you are using {uri-flycheck}[Flycheck] and not Flymake, check
out a similar project, {uri-flycheck-eldev}[flycheck-eldev]

== Features

* No additional steps to be performed from the command line, not even
  `eldev prepare`.

* Project dependencies are seen by Flymake in Emacs.  Similarly, if a
  package is not declared as a dependency of your project, Flymake
  will complain about unimportable features or undeclared functions.

* Everything is done on-the-fly.  As you edit your project’s
  dependency list in its main `.el` file, added, removed or mistyped
  dependency names immediately become available to Flymake (there
  might be some delays due to network, as Eldev needs to fetch them
  first).

* Additional test dependencies (see `eldev-add-extra-dependencies`)
  are seen from the test files, but not from the main files.

* Also checks files `Eldev` and `Eldev-local` (as long as they are
  byte-compilable, but this is a common Flymake requirement).  Detect
  wrong `(eldev-...)` function calls as you type!

== Installation

Download and install the package from {uri-melpa-stable}[MELPA Stable]
or {uri-melpa-unstable}[MELPA].  No further steps necessary: once the
package is installed, it is active and Flymake will detect any Eldev
projects on-the-fly.

For the extension to have any effect, you need to
{uri-eldev-installation}[install Eldev].

If you want to deactivate the package for some reason, set variable
`flymake-eldev-active` to nil.
